#!/usr/bin/dh-exec

dockerversion usr/share/gocode/src/${DH_GOPKG}/
.gopath/src/github.com/docker/docker/pkg usr/share/gocode/src/${DH_GOPKG}/
.gopath/src/github.com/docker/docker/opts usr/share/gocode/src/${DH_GOPKG}/
.gopath/src/github.com/docker/docker/api usr/share/gocode/src/${DH_GOPKG}/
.gopath/src/github.com/docker/docker/client usr/share/gocode/src/${DH_GOPKG}/
.gopath/src/github.com/docker/docker/cliconfig usr/share/gocode/src/${DH_GOPKG}/
.gopath/src/github.com/docker/docker/reference usr/share/gocode/src/${DH_GOPKG}/
.gopath/src/github.com/docker/docker/registry usr/share/gocode/src/${DH_GOPKG}/
.gopath/src/github.com/docker/docker/runconfig usr/share/gocode/src/${DH_GOPKG}/
