.gopath/src/github.com/docker/cli/cli/config              usr/share/gocode/src/github.com/docker/cli/cli/
.gopath/src/github.com/docker/cli/opts                    usr/share/gocode/src/github.com/docker/cli/
.gopath/src/github.com/docker/cli/internal/test/testutil  usr/share/gocode/src/github.com/docker/cli/internal/test/

## compatibility with older Docker
.gopath/src/github.com/docker/cli/cli/config/*      usr/share/gocode/src/github.com/docker/docker/cliconfig/
#.gopath/src/github.com/docker/cli/cli/config/*      usr/share/gocode/src/github.com/docker/docker/cli/config/

engine/dockerversion                                usr/share/gocode/src/github.com/docker/docker/

.gopath/src/github.com/docker/docker/api            usr/share/gocode/src/github.com/docker/docker/
.gopath/src/github.com/docker/docker/cli            usr/share/gocode/src/github.com/docker/docker/
.gopath/src/github.com/docker/docker/client         usr/share/gocode/src/github.com/docker/docker/
.gopath/src/github.com/docker/docker/opts           usr/share/gocode/src/github.com/docker/docker/
.gopath/src/github.com/docker/docker/pkg            usr/share/gocode/src/github.com/docker/docker/
.gopath/src/github.com/docker/docker/reference      usr/share/gocode/src/github.com/docker/docker/
.gopath/src/github.com/docker/docker/registry       usr/share/gocode/src/github.com/docker/docker/
.gopath/src/github.com/docker/docker/runconfig      usr/share/gocode/src/github.com/docker/docker/


## Libnetwork:
.gopath/src/github.com/docker/libnetwork/datastore        usr/share/gocode/src/github.com/docker/libnetwork/
.gopath/src/github.com/docker/libnetwork/discoverapi      usr/share/gocode/src/github.com/docker/libnetwork/
.gopath/src/github.com/docker/libnetwork/ns               usr/share/gocode/src/github.com/docker/libnetwork/
.gopath/src/github.com/docker/libnetwork/options          usr/share/gocode/src/github.com/docker/libnetwork/
.gopath/src/github.com/docker/libnetwork/testutils        usr/share/gocode/src/github.com/docker/libnetwork/
.gopath/src/github.com/docker/libnetwork/types            usr/share/gocode/src/github.com/docker/libnetwork/


## Sub-vendoring:
engine/vendor/github.com/containerd/continuity/driver        usr/share/gocode/src/github.com/docker/docker/vendor/github.com/containerd/continuity/
engine/vendor/github.com/containerd/continuity/pathdriver    usr/share/gocode/src/github.com/docker/docker/vendor/github.com/containerd/continuity/

engine/vendor/github.com/gotestyourself/gotestyourself/skip  usr/share/gocode/src/github.com/docker/docker/vendor/github.com/gotestyourself/gotestyourself/

engine/vendor/github.com/Nvveen/Gotty                        usr/share/gocode/src/github.com/docker/docker/vendor/github.com/Nvveen/

distribution/reference                                       usr/share/gocode/src/github.com/docker/docker/vendor/github.com/docker/distribution/
distribution/digestset                                       usr/share/gocode/src/github.com/docker/docker/vendor/github.com/docker/distribution/
